/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\eiffel-high.glb -Ttse
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Tour_Eiffel: THREE.Mesh;
  };
  materials: object;
};

export function EiffelHigh(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/eiffel/eiffel-high-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tour_Eiffel.geometry}
        position={[-0.283, 0.478, 0.56]}
        scale={[0.026, 0.005, 0.005]}
      >
        <meshStandardMaterial
          // by night
          // color="#81310e"
          // by day
          color="#ffac81"
          emissive={"#111"}
          metalness={0.95}
          roughness={0.45}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/eiffel/eiffel-high-transformed.glb");
