/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\eiffel-low.glb -Ttse
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Tour_Eiffel: THREE.Mesh;
  };
  materials: object;
};

export function EiffelLow(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/eiffel/eiffel-low-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tour_Eiffel.geometry}
        position={[-0.283, 0.478, 0.56]}
        scale={[0.026, 0.005, 0.005]}
      >
        <meshBasicMaterial color="#f85" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/eiffel/eiffel-low-transformed.glb");
