/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\eiffel_base.glb --transform
*/

import { a, useSpring } from "@react-spring/three";
import { FC, useMemo } from "react";
import { GroupProps } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { ColorScheme, useColorScheme } from "../../hooks/useColorScheme";

const EiffelBase: FC<GroupProps> = (props) => {
  const { nodes } = useGLTF("/eiffel/eiffel_base-transformed.glb");

  // Retrieve the user's color scheme
  const scheme = useColorScheme();

  // Material selection based on the color scheme
  const material = useMemo(() => {
    if (scheme === ColorScheme.Dark) {
      return <meshStandardMaterial color="#333333" roughness={0.3} />;
    }

    return <meshStandardMaterial color="#ffffff" roughness={0.3} />;
  }, [scheme]);

  const [animation] = useSpring(() => ({
    from: {
      scale: 0,
    },
    to: {
      scale: 1,
    },
    delay: 0,
  }));

  return (
    <a.group {...props} scale={animation.scale} dispose={null}>
      <mesh
        // @ts-expect-error expected
        geometry={nodes.base.geometry}
        position={[-0.283, 0.478, 0.56]}
        scale={[0.026, 0.005, 0.005]}
        castShadow
        receiveShadow
      >
        {material}
      </mesh>
    </a.group>
  );
};

useGLTF.preload("/eiffel/eiffel_base-transformed.glb");

export default EiffelBase;
