/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsSplatImport } from './routes/posts/$'

// Create Virtual Routes

const ExperimentsOtterLazyImport = createFileRoute('/experiments/otter')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperimentsOtterLazyRoute = ExperimentsOtterLazyImport.update({
  path: '/experiments/otter',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/experiments/otter.lazy').then((d) => d.Route),
)

const PostsSplatRoute = PostsSplatImport.update({
  path: '/posts/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$': {
      id: '/posts/$'
      path: '/posts/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof PostsSplatImport
      parentRoute: typeof rootRoute
    }
    '/experiments/otter': {
      id: '/experiments/otter'
      path: '/experiments/otter'
      fullPath: '/experiments/otter'
      preLoaderRoute: typeof ExperimentsOtterLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/experiments/otter': typeof ExperimentsOtterLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/experiments/otter': typeof ExperimentsOtterLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/experiments/otter': typeof ExperimentsOtterLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$' | '/experiments/otter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$' | '/experiments/otter'
  id: '__root__' | '/' | '/posts/$' | '/experiments/otter'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsSplatRoute: typeof PostsSplatRoute
  ExperimentsOtterLazyRoute: typeof ExperimentsOtterLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsSplatRoute: PostsSplatRoute,
  ExperimentsOtterLazyRoute: ExperimentsOtterLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/$",
        "/experiments/otter"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/$": {
      "filePath": "posts/$.tsx"
    },
    "/experiments/otter": {
      "filePath": "experiments/otter.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
