/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\Pumpkin_round.glb -Tt
*/

import { a, useSpring } from "@react-spring/three";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
    lambert3SG: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/halloween/Pumpkin_round-transformed.glb"
  ) as GLTFResult;

  const [animation] = useSpring(
    () => ({
      from: {
        scale: 0,
      },
      to: {
        scale: props.scale ?? 1,
      },
    }),
    [props.scale]
  );

  return (
    <a.group {...props} scale={animation.scale} dispose={null}>
      <mesh
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.lambert2SG}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.lambert3SG}
        castShadow
        receiveShadow
      />
    </a.group>
  );
}

useGLTF.preload("/halloween/Pumpkin_round-transformed.glb");

export default Model;
