/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\snowman.glb -Tt
*/

import { a, useSpring } from "@react-spring/three";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useState } from "react";

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    left_eye: THREE.Mesh;
    nose: THREE.Mesh;
    button_middle: THREE.Mesh;
  };
  materials: {
    snownman_body: THREE.MeshStandardMaterial;
    snowman_eye: THREE.MeshStandardMaterial;
    snowman_carrot_nose: THREE.MeshStandardMaterial;
    snowman_buttons: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/christmas/snowman-transformed.glb"
  ) as GLTFResult;

  const [jump, setJump] = useState<boolean>(false);

  const [animation] = useSpring(
    () => ({
      from: {
        scale: 0,
      },
      to: {
        scale: props.scale ?? 1,
      },
    }),
    [props.scale]
  );

  const [animateJump] = useSpring(
    () => ({
      from: {
        y: (props.position as number[])?.[1] ?? 0,
      },
      to: {
        y: ((props.position as number[])?.[1] ?? 0) + 0.2,
      },
      reverse: !jump,
      config: {
        duration: 200,
      },
      onResolve: () => setJump(false),
    }),
    [jump, props.position]
  );

  return (
    <a.group
      {...props}
      scale={animation.scale}
      position-y={animateJump.y}
      dispose={null}
      onClick={() => setJump(true)}
    >
      <mesh
        geometry={nodes.body.geometry}
        // @ts-expect-error does not have a type
        material={materials.PaletteMaterial001}
        position={[0, 1, 0]}
      />
      <mesh
        geometry={nodes.left_eye.geometry}
        // @ts-expect-error does not have a type
        material={materials.PaletteMaterial002}
        position={[0.3, 2.5, 0.541]}
      />
      <mesh
        geometry={nodes.nose.geometry}
        // @ts-expect-error does not have a type
        material={materials.PaletteMaterial003}
        position={[0, 2.25, 0.8]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </a.group>
  );
}

useGLTF.preload("/christmas/snowman-transformed.glb");

export default Model;
