/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\SquaredChristmasGifts.glb -Tt
*/

import { a, useSpring } from "@react-spring/three";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
    ["Node-Mesh_2"]: THREE.Mesh;
    ["Node-Mesh_3"]: THREE.Mesh;
  };
  materials: {
    mat8: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/christmas/SquaredChristmasGifts-transformed.glb"
  ) as GLTFResult;

  const [animation] = useSpring(
    () => ({
      from: {
        scale: 0,
      },
      to: {
        scale: props.scale ?? 1,
      },
    }),
    [props.scale]
  );

  return (
    <a.group {...props} scale={animation.scale} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat8} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes["Node-Mesh_3"].geometry}
        material={materials.mat12}
      />
    </a.group>
  );
}

useGLTF.preload("/christmas/SquaredChristmasGifts-transformed.glb");

export default Model;
