/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\ChristmasPresents.glb -Tt
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    group749557293: THREE.Mesh;
    group1886123043: THREE.Mesh;
    group1262929608: THREE.Mesh;
  };
  materials: {
    mat21: THREE.MeshStandardMaterial;
    mat8: THREE.MeshStandardMaterial;
    mat10: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/christmas/ChristmasPresents-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.group749557293.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1886123043.geometry}
        material={materials.mat8}
      />
      <mesh
        geometry={nodes.group1262929608.geometry}
        material={materials.mat10}
      />
    </group>
  );
}

useGLTF.preload("/christmas/ChristmasPresents-transformed.glb");

export default Model;
