/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\Pumpkin_round.glb -Tt
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
    lambert3SG: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/halloween/Pumpkin_round-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.lambert2SG}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.lambert3SG}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/Pumpkin_round-transformed.glb");

export default Model;
