/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\Scarecrow.glb -Tt
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Scarecrow_mesh: THREE.Mesh;
  };
  materials: {
    Scarecrow_mat1: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/halloween/Scarecrow-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scarecrow_mesh.geometry}
        material={materials.Scarecrow_mat1}
      />
    </group>
  );
}

useGLTF.preload("/halloween/Scarecrow-transformed.glb");

export default Model;
